# Generated by Django 3.1.14 on 2022-06-25 12:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Title Certificate',
                'verbose_name_plural': 'Titles Certificate',
            },
        ),
        migrations.CreateModel(
            name='TitleWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'TitleWork',
                'verbose_name_plural': 'TitlesWork',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='Ip')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Image', models.ImageField(null=True, upload_to='Images/Me', verbose_name='Image Me')),
                ('Age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('Date_Of_Birth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date Of Birth')),
                ('Address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('Degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='Degree')),
                ('Freelance', models.CharField(max_length=50, null=True, verbose_name='Freelance')),
                ('About_Me', models.TextField(max_length=500, null=True, verbose_name='About Me')),
                ('HappyClients', models.IntegerField(null=True, verbose_name='Happy Clients')),
                ('Projects', models.IntegerField(null=True, verbose_name='Projects')),
                ('HoursOfSupport', models.IntegerField(null=True, verbose_name='Hours Of Support')),
                ('Awards', models.IntegerField(null=True, verbose_name='Awards')),
                ('Instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram')),
                ('GitHub', models.CharField(blank=True, max_length=50, null=True, verbose_name='Github')),
                ('Linkedin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Linkedin')),
                ('Phone', models.CharField(max_length=13, null=True, verbose_name='Phone')),
                ('Web_Site', models.URLField(max_length=100, verbose_name='Web Site')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'AboutMe',
                'verbose_name_plural': 'AboutsMe',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_Do', models.CharField(blank=True, max_length=50, null=True, verbose_name='I_Do')),
                ('Link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('Image', models.ImageField(upload_to='Images/WorkSample/', verbose_name='Image')),
                ('Is_Active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='About_Me.titlework', verbose_name='عنوان')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Me')),
            ],
            options={
                'verbose_name': 'WorkSample',
                'verbose_name_plural': 'WorkSamples',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Title')),
                ('Percentage', models.IntegerField(verbose_name='Percentage')),
                ('Is_Active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Me')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='JobTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Title')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Me')),
            ],
            options={
                'verbose_name': 'JobTitle',
                'verbose_name_plural': 'JobTitles',
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('Work', models.CharField(max_length=50, verbose_name='Work')),
                ('Date', models.CharField(max_length=10, verbose_name='Date')),
                ('Is_Active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Me')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Majors', models.CharField(max_length=50, verbose_name='Majors')),
                ('Educational_Degree', models.CharField(max_length=50, verbose_name='Educational Degree')),
                ('Comment', models.TextField(max_length=307, verbose_name='Comment')),
                ('CreateTime', models.DateField(auto_now_add=True, max_length=10, verbose_name='CreateTime')),
                ('Address', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('Is_Active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Me')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200, verbose_name='Description')),
                ('Experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='About_Me.experiences', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Description of the experience',
                'verbose_name_plural': 'Description of experiences',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50, verbose_name='Full Name')),
                ('EmailAddress', models.EmailField(max_length=254, verbose_name='EmailAddress')),
                ('Subject', models.CharField(max_length=50, null=True, verbose_name='Subject')),
                ('Message', models.TextField(max_length=500, verbose_name='Message')),
                ('Is_Read_Admin', models.BooleanField(default=False, verbose_name='Is_Read_Admin')),
                ('user', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Me')),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='CommentsOfOthersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='Images/Comment/', verbose_name='Image')),
                ('FullName', models.CharField(max_length=50, verbose_name='Full Name')),
                ('Comments', models.TextField(max_length=307, verbose_name='Comments')),
                ('Job', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job')),
                ('Is_Read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comments Of Others')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage', models.IntegerField(verbose_name='Percent')),
                ('Image', models.ImageField(upload_to='Images/Skills', verbose_name='Photo of the document')),
                ('Url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Url')),
                ('Is_Active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('Title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='About_Me.titlecertificate', verbose_name='Title')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Me')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
