# Generated by Django 3.1.14 on 2022-06-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About_Me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='Comment',
        ),
    ]
