# Generated by Django 3.2.13 on 2022-06-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('About_Me', '0006_auto_20220627_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='About_Me.certificatecategory', verbose_name='Category'),
        ),
    ]
