# Generated by Django 3.2.13 on 2022-06-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About_Me', '0007_alter_certificate_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='Category',
            new_name='CertificateCategory',
        ),
    ]
