# Generated by Django 3.2.13 on 2022-06-27 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('About_Me', '0008_rename_category_certificate_certificatecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsofothersmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
