# Generated by Django 3.2.13 on 2022-06-27 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('About_Me', '0009_alter_commentsofothersmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksamples',
            name='Client',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='CertificateCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='About_Me.certificatecategory', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='commentsofothersmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comments Of Others'),
        ),
        migrations.AlterField(
            model_name='worksamplegallery',
            name='Image',
            field=models.FileField(null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='worksamples',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='About_Me.worksamplecategory', verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='worksamples',
            name='Company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
    ]
